### ISSUE TITLE
After upgrade to 2023.5.2 the component does not load

### ISSUE THREAD

**Issue by tolrahC** [travisghansen/hass-pfsense#162]
Unable to import component: cannot import name 'async_get_registry' from 'homeassistant.helpers.entity_registry'.

As per [this](https://community.home-assistant.io/t/2023-5-lets-talk/567331/23), the get_registry method as been deprecated.

**Comment by travisghansen** [comment]
Was fixed in `v0.6.1` released several days ago.

**Comment by tolrahC** [comment]
> Was fixed in `v0.6.1` released several days ago.

🤦‍♂️, I forgot it was an HACS integration, I just did the update and it is working fine.

Sorry about that
